### ISSUE TITLE
`Freiburg` vs `Freiburg im Breisgau`

### ISSUE THREAD

**Issue by S1SYPHOS** [lokal-ninja/baden-wuerttemberg#2]
Hey there,
before contributing to this project, I'd like to know why there are duplicate entries for Freiburg - my guess would be that one folder was imported from OSM, the other contains manual entries?

Thanks for letting me know, cheers
S1SYPHOS

**Comment by midzer** [comment]
Hi S1SYPHOS,

thanks for your issue. Sorry, for my late answer.

I have no clue why there are two `Freiburg` in the data. All information has been fetched from up to date OSM .pbf files, then converted to markdown files, run through Hugo static site generator and finally deployed to a web hoster.

Have a nice week
midzer

**Comment by S1SYPHOS** [comment]
So if I wanted to contribute, which one should it be? ❓

**Comment by midzer** [comment]
About this exact issue I think it's better to ask some1 from the OSM community directly (on https://www.oftc.net/ IRC #osm-de for example).

If you want to contribute to Shoogle theme or architecture itself, feel free to open an issue in https://github.com/lokal-ninja/ln-base and we can talk about it.

**Comment by midzer** [comment]
I think we can close this issue for good.

If you have further questions, feel free to reopen or contact me.

**Comment by S1SYPHOS** [comment]
Fine by me!
